### ISSUE TITLE
Death by burning with urn doesn't result in becoming undead (Incompatibility)

### ISSUE THREAD

**Issue by Cat-McCatface** [palaster/BloodBank#7]
If player has a grave mod installed (Tomb Many Graves in test instance) death is overridden by other mod resulting in player not becoming zambie. Urn is used in process but not obtained back from grave block indicating some code was executed. Other mods that alter death (Fez) work as intended (item is consumed preventing player death and grave generation).

mod version: 0.6.2
MC: 1.9.4
forge: 1954

**Comment by Cat-McCatface** [comment]
Tested with tomb many graves removed.
Result: inventory not lost. Urn consumed. Death screen occurred.

Not sure if intended behaviour or not.

edit: testing with EnderIO removed to eliminate even a bug of the soulbound enchantment from altering death process. same result

**Comment by palaster** [comment]
The urn is not returned in process when you die with it in fire. But, the rest of your inventory should drop which it did because it was picked up by the grave mod. Being undead is not a visually noticeable, you will know if your undead if you can use the undead monitor. Because if you weren't undead you wouldn't be able to use the undead monitor to open the menu.

**Comment by Cat-McCatface** [comment]
makes sense

**Comment by palaster** [comment]
Also, being undead is like being unkindled from the dark souls franchise, not an actually zombie.
